disabled_rules:
 - force_cast
 
excluded: # case-sensitive paths to ignore during linting. Takes precedence over `included`
    - "/Users/abhishek-sreejith/Desktop/Abhishek/Milestone4/Milestone 4/Models/EmployeeData.swift"
    - "/Users/abhishek-sreejith/Desktop/Abhishek/Milestone4/Milestone 4/Models/ChatManager.swift"
  #- "/Users/abhishek-sreejith/Desktop/Abhishek/Milestone4/Milestone 4/Models/ChatManager.swift"
    - Carthage
    - Pods
  #- /Users/abhishek-sreejith/Desktop/Abhishek/Milestone4/Milestone\ 4/Models/EmployeeData.swift
  
line_length: 300

